-- MySQL Script generated by MySQL Workbench
-- Sun Dec  5 17:50:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre_usuario` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `Estado_usuario` INT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `idProducto` INT NOT NULL,
  `Nombre_producto` VARCHAR(45) NULL,
  `Cantidad_producto` INT NULL,
  `id_ingreso_producto` INT NULL,
  `id_egreso_producto` INT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Inventario_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Condominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Condominio` (
  `idCondominio` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `RIF` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Numero_telefonico` VARCHAR(45) NULL,
  `Correo_electronico` VARCHAR(45) NULL,
  `Inventario_idProducto` INT NOT NULL,
  PRIMARY KEY (`idCondominio`),
  INDEX `fk_Condominio_Inventario1_idx` (`Inventario_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Condominio_Inventario1`
    FOREIGN KEY (`Inventario_idProducto`)
    REFERENCES `mydb`.`Inventario` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura de Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura de Pago` (
  `idFactura de Pago` INT NOT NULL,
  `Fecha` DATETIME NULL,
  `Monto_total_bolivares` FLOAT NULL,
  `Monto_total_dolares` FLOAT NULL,
  `Porcentaje_alicuota` INT NULL,
  PRIMARY KEY (`idFactura de Pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hogar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hogar` (
  `idHogar` INT NOT NULL,
  `Referencia_casa` VARCHAR(45) NULL,
  `Referenca_apartamento` VARCHAR(45) NULL,
  `Referencia_hogar` VARCHAR(45) NULL,
  `Referencia_piso` VARCHAR(45) NULL,
  `Referencia_torre` VARCHAR(45) NULL,
  `Factura de Pago_idFactura de Pago` INT NOT NULL,
  PRIMARY KEY (`idHogar`),
  INDEX `fk_Hogar_Factura de Pago1_idx` (`Factura de Pago_idFactura de Pago` ASC) VISIBLE,
  CONSTRAINT `fk_Hogar_Factura de Pago1`
    FOREIGN KEY (`Factura de Pago_idFactura de Pago`)
    REFERENCES `mydb`.`Factura de Pago` (`idFactura de Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conjunto Residencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conjunto Residencial` (
  `idConjunto Residencial` INT NOT NULL,
  `Nombre_conjuntores` VARCHAR(45) NULL,
  `RIF_conjuntores` VARCHAR(45) NULL,
  `Direccion_conjuntores` VARCHAR(45) NULL,
  `Pais` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Municipio` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Hogar_idHogar` INT NOT NULL,
  PRIMARY KEY (`idConjunto Residencial`, `Hogar_idHogar`),
  INDEX `fk_Conjunto Residencial_Hogar1_idx` (`Hogar_idHogar` ASC) VISIBLE,
  CONSTRAINT `fk_Conjunto Residencial_Hogar1`
    FOREIGN KEY (`Hogar_idHogar`)
    REFERENCES `mydb`.`Hogar` (`idHogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Torre Apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Torre Apartamento` (
  `idTorre Apartamento` INT NOT NULL,
  `Nombre_torre` VARCHAR(45) NULL,
  `Numero_apartamento` INT NULL,
  `Numero_pisos` INT NULL,
  `Calles` VARCHAR(45) NULL,
  PRIMARY KEY (`idTorre Apartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuotas` (
  `idCuotas` INT NOT NULL,
  `Descripcion_cuota` VARCHAR(45) NULL,
  `Monto_cuota` FLOAT NULL,
  PRIMARY KEY (`idCuotas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico de Operaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico de Operaciones` (
  `idHistorico de Operaciones` INT NOT NULL,
  `Registro_operacion` VARCHAR(45) NULL,
  `Factura de Pago_idFactura de Pago` INT NOT NULL,
  PRIMARY KEY (`idHistorico de Operaciones`),
  INDEX `fk_Historico de Operaciones_Factura de Pago1_idx` (`Factura de Pago_idFactura de Pago` ASC) VISIBLE,
  CONSTRAINT `fk_Historico de Operaciones_Factura de Pago1`
    FOREIGN KEY (`Factura de Pago_idFactura de Pago`)
    REFERENCES `mydb`.`Factura de Pago` (`idFactura de Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caja` (
  `idCaja` INT NOT NULL,
  `Fondo_reserva` FLOAT NULL,
  `Fondo_especial` FLOAT NULL,
  `Fondo_prestaciones` FLOAT NULL,
  `Fondo_Movistar` FLOAT NULL,
  `IdIngreso` INT NULL,
  `IdEgreso` INT NULL,
  `Monto_ingreso` FLOAT NULL,
  `Monto_egreso` FLOAT NULL,
  `Factura de Pago_idFactura de Pago` INT NOT NULL,
  `Condominio_idCondominio` INT NOT NULL,
  PRIMARY KEY (`idCaja`, `Factura de Pago_idFactura de Pago`, `Condominio_idCondominio`),
  INDEX `fk_Caja_Factura de Pago1_idx` (`Factura de Pago_idFactura de Pago` ASC) VISIBLE,
  INDEX `fk_Caja_Condominio1_idx` (`Condominio_idCondominio` ASC) VISIBLE,
  CONSTRAINT `fk_Caja_Factura de Pago1`
    FOREIGN KEY (`Factura de Pago_idFactura de Pago`)
    REFERENCES `mydb`.`Factura de Pago` (`idFactura de Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caja_Condominio1`
    FOREIGN KEY (`Condominio_idCondominio`)
    REFERENCES `mydb`.`Condominio` (`idCondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Condominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Condominio` (
  `Usuario_idUsuario` INT NOT NULL,
  `Condominio_idCondominio` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Condominio_idCondominio`),
  INDEX `fk_Usuario_has_Condominio_Condominio1_idx` (`Condominio_idCondominio` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Condominio_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Condominio_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Condominio_Condominio1`
    FOREIGN KEY (`Condominio_idCondominio`)
    REFERENCES `mydb`.`Condominio` (`idCondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hogar_has_Torre Apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hogar_has_Torre Apartamento` (
  `Hogar_idHogar` INT NOT NULL,
  `Torre Apartamento_idTorre Apartamento` INT NOT NULL,
  PRIMARY KEY (`Hogar_idHogar`, `Torre Apartamento_idTorre Apartamento`),
  INDEX `fk_Hogar_has_Torre Apartamento_Torre Apartamento1_idx` (`Torre Apartamento_idTorre Apartamento` ASC) VISIBLE,
  INDEX `fk_Hogar_has_Torre Apartamento_Hogar1_idx` (`Hogar_idHogar` ASC) VISIBLE,
  CONSTRAINT `fk_Hogar_has_Torre Apartamento_Hogar1`
    FOREIGN KEY (`Hogar_idHogar`)
    REFERENCES `mydb`.`Hogar` (`idHogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hogar_has_Torre Apartamento_Torre Apartamento1`
    FOREIGN KEY (`Torre Apartamento_idTorre Apartamento`)
    REFERENCES `mydb`.`Torre Apartamento` (`idTorre Apartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Condominio_has_Conjunto Residencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Condominio_has_Conjunto Residencial` (
  `Condominio_idCondominio` INT NOT NULL,
  `Conjunto Residencial_idConjunto Residencial` INT NOT NULL,
  `Conjunto Residencial_Hogar_idHogar` INT NOT NULL,
  PRIMARY KEY (`Condominio_idCondominio`, `Conjunto Residencial_idConjunto Residencial`, `Conjunto Residencial_Hogar_idHogar`),
  INDEX `fk_Condominio_has_Conjunto Residencial_Conjunto Residencial_idx` (`Conjunto Residencial_idConjunto Residencial` ASC, `Conjunto Residencial_Hogar_idHogar` ASC) VISIBLE,
  INDEX `fk_Condominio_has_Conjunto Residencial_Condominio1_idx` (`Condominio_idCondominio` ASC) VISIBLE,
  CONSTRAINT `fk_Condominio_has_Conjunto Residencial_Condominio1`
    FOREIGN KEY (`Condominio_idCondominio`)
    REFERENCES `mydb`.`Condominio` (`idCondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Condominio_has_Conjunto Residencial_Conjunto Residencial1`
    FOREIGN KEY (`Conjunto Residencial_idConjunto Residencial` , `Conjunto Residencial_Hogar_idHogar`)
    REFERENCES `mydb`.`Conjunto Residencial` (`idConjunto Residencial` , `Hogar_idHogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuotas_has_Factura de Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuotas_has_Factura de Pago` (
  `Cuotas_idCuotas` INT NOT NULL,
  `Factura de Pago_idFactura de Pago` INT NOT NULL,
  PRIMARY KEY (`Cuotas_idCuotas`, `Factura de Pago_idFactura de Pago`),
  INDEX `fk_Cuotas_has_Factura de Pago_Factura de Pago1_idx` (`Factura de Pago_idFactura de Pago` ASC) VISIBLE,
  INDEX `fk_Cuotas_has_Factura de Pago_Cuotas1_idx` (`Cuotas_idCuotas` ASC) VISIBLE,
  CONSTRAINT `fk_Cuotas_has_Factura de Pago_Cuotas1`
    FOREIGN KEY (`Cuotas_idCuotas`)
    REFERENCES `mydb`.`Cuotas` (`idCuotas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuotas_has_Factura de Pago_Factura de Pago1`
    FOREIGN KEY (`Factura de Pago_idFactura de Pago`)
    REFERENCES `mydb`.`Factura de Pago` (`idFactura de Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
